import type { FsDir } from "./filesystemWorag";

/**
 * Layards Manuskript-Ordner: das Hörspiel-Treatment
 * »TOTER BRIEFKASTEN« (Fassung Herbst 1997).
 *
 * Ausgelagert aus `filesystemWorag.ts`, damit der
 * Haupt-Baum lesbar bleibt. Wird dort unter
 * /home/layard/manuskripte eingehängt.
 */
export const MANUSKRIPTE_DIR: FsDir = {
  type: "dir",
  name: "manuskripte",
  desc: "Eigene Texte. Nicht dienstlich.",
  children: [
    {
      type: "dir",
      name: "toter_briefkasten",
      desc: "Hörspiel-Treatment, Fassung Herbst 1997.",
      children: [
        {
          type: "file",
          name: "00_LIESMICH.txt",
          kind: "text",
          size: 860,
          date: "14.11.1997",
          content: [
            "── STAND DER BEARBEITUNG ───────────────────────────────────",
            "",
            "Diese Fassung ist nicht eingereicht. Ich habe sie zweimal",
            "überarbeitet und einmal beiseitegelegt, für beinahe ein",
            "Jahr. Ob ich sie beim Bürgerfunk vorlege, weiß ich nicht.",
            "Vielleicht genügt es, dass sie geschrieben ist.",
            "",
            "Sechs Dateien, in Lesereihenfolge nummeriert.",
            "Die Szene in 06 ist die einzige Stelle, an der",
            "ich weiß, wie es klingen soll.",
            "",
            "L. W.",
            "",
            "── Ende ────────────────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "01_titelblatt.txt",
          kind: "text",
          size: 980,
          date: "14.11.1997",
          content: [
            "── TOTER BRIEFKASTEN ───────────────────────────────────────",
            "",
            "        T O T E R   B R I E F K A S T E N",
            "",
            "        Verwaltungsdrama in drei Akten",
            "",
            "Genre:      Kammerspiel / Verwaltungsdrama",
            "Format:     Hörspiel, ca. 70 Minuten",
            "Vorgesehen: Bürgerfunk, Abendprogramm",
            "Autor:      L. Worag, Sektor 28, Zimmer 2611",
            "Fassung:    Herbst 1997",
            "",
            "Figuren, Ressorts und Vorgänge frei erfunden.",
            "Jede Ähnlichkeit mit bestehenden Vorgängen ist",
            "nicht beabsichtigt und wäre auch nicht belegbar.",
            "",
            "── Ende ────────────────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "02_logline_synopsis.txt",
          kind: "text",
          size: 4200,
          date: "02.09.1997",
          content: [
            "── 1. LOGLINE & KURZSYNOPSIS ───────────────────────────────",
            "",
            "Logline",
            "",
            "Sektor 28, 1996: Um in der ZDS-Redaktion zu bestehen, muss",
            "Konrad Fenner, Redakteur der Jubiläums-Sondersendung zum",
            "fünfzigsten Gründungstag des Mandatsgebiets, eine",
            "Zuversicht vorspielen, die er selbst längst verloren hat —",
            "und wird darin so vollkommen, dass er nicht mehr weiß, wo",
            "die Maske endet und er beginnt. Als sein Vorgesetzter,",
            "Oberrat Brekke, ihm im Austausch für ein makelloses",
            "Sendemanuskript ein vergrabenes Kapitel der",
            "Mandatsgeschichte anvertraut, wird aus Konrads stiller",
            "Sorgfalt ein Wettlauf gegen die Frist, in dem ein einziges",
            "falsches Wort nicht nur ihn, sondern eine fünfzig Jahre",
            "alte Erzählung zu Fall bringen kann.",
            "",
            "Kurzsynopsis",
            "",
            "",
            "Sektor 28, im Herbst 1996. Der Bürgerfunk bereitet die",
            "Sondersendung zum fünfzigjährigen Bestehen des",
            "Mandatsgebiets vor, und die Stimmung in der Redaktion ist",
            "eine Art Erschöpfung, die sich als Feierlaune tarnt.",
            "KONRAD FENNER, 41, Redakteur im Ressort Sektorbericht,",
            "gehört zu den Männern, die diese Feierlaune mitverfassen.",
            "Was in der Redaktion niemand weiß: Konrad hat vor Jahren,",
            "im Zuge seiner regulären Archivarbeit, angefangen,",
            "Dokumente beiseitezulegen, die nicht in die offizielle",
            "Erzählung passen — nicht aus Plan, sondern aus einer",
            "Gewohnheit, die er selbst nicht recht benennen kann. Seine",
            "Waffe ist nicht die Pistole, sondern die perfekte",
            "Imitation von Zuversicht.",
            "",
            "Als OBERRAT BREKKE ihn mit der Leitung der",
            "Jubiläumssendung betraut — einem Sonderformat, das nicht",
            "die längst Überzeugten, sondern die zunehmend erschöpften",
            "Sektorbewohner erreichen soll —, sieht Konrad seine",
            "Chance: Zugang zum Zentralarchiv, zu Beständen, die für",
            "die reguläre Registratur gesperrt sind. Doch die Chance",
            "ist eine Falle mit zwei Seiten: Je überzeugender seine",
            "Sendung, je wärmer sein Ton, desto wirksamer dient er",
            "womöglich genau der Erzählung, die er insgeheim zu",
            "unterlaufen sucht.",
            "",
            "Bei einer nächtlichen Archivrecherche im Wohnblock gerät",
            "Konrad in einen unangenehmen Zwischenfall mit dem",
            "verängstigten Hausmeister TORBEN PAHL — der ihn für einen",
            "Kontrolleur hält — und gewinnt daraus, behutsam, ein",
            "erstes Verbündetenpaar: Torben und seine Frau NELE,",
            "bürgerlich, vorsichtig, aber bereit, im Kleinen zu helfen.",
            "Aus ihrer zurückhaltenden Freundschaft wird eine kleine,",
            "informelle Ablagestelle für das, was Konrad nicht in der",
            "Redaktion aufbewahren kann.",
            "",
            "Konrads Konzept für die Sondersendung: das Jubiläum nicht",
            "als Triumph, sondern als offene Frage zu erzählen —",
            "menschlich genug, brüchig genug, dass die glatte Erzählung",
            "von innen zu bröckeln beginnt. Die zugeteilte",
            "Chefredaktion ist linientreu und wachsam; jede Abweichung",
            "muss sich als gesteigerte Sendequalität tarnen. Genau",
            "darin liegt die Falle: Was als leise Korrektur gedacht",
            "ist, lässt sich mühelos als bewegendere, überzeugendere",
            "Jubiläumserzählung lesen. Niemand — am wenigsten Konrad",
            "selbst — kann am Ende sagen, ob seine Sendung die",
            "Erzählung schwächt oder perfektioniert.",
            "",
            "Der Wendepunkt: Beeindruckt von Konrads scheinbarer",
            "Hingabe, zieht Brekke ihn in sein engstes Vertrauen — und",
            "offenbart in einem kühlen Gespräch unter vier Augen ein",
            "Aktenfragment aus dem Gründungsjahrzehnt: Belege, dass die",
            "„vorläufige\" Verwaltung 1971, im Zuge der Quadranten-",
            "Konvention, in eine echte, verhandelbare Souveränität",
            "hätte überführt werden können — und dass sich die damalige",
            "Mandatsverwaltung, aus Gründen, die die Akte nur andeutet,",
            "aktiv dagegen entschied. Das Wissen ist Geschenk und",
            "Halsband zugleich: Wer es trägt, ist Mitwisser. Im",
            "gleichen Atemzug fordert Brekke das fertige",
            "Sendemanuskript — als Pfand für Konrads Loyalität.",
            "",
            "Konrad gibt eine Abschrift des Aktenfragments über eine",
            "stillgelegte Rohrpost-Station weiter, mit der",
            "ausdrücklichen Selbstauflage, sie nicht leichtfertig",
            "weiterzugeben — wobei unklar bleibt, wessen Hände die",
            "richtigen wären. Eine Antwort kommt nie. Die Stille wird",
            "zu einer eigenen Form der Prüfung.",
            "",
            "Während die Sendung Gestalt annimmt und der",
            "Jubiläumstermin näherrückt, verdichten sich die Zeichen",
            "der Beobachtung: eine Kollegin, die eine Frage zu genau",
            "stellt; die Rohrpost-Station, die einmal anders aussieht,",
            "als Konrad sie verlassen hat; Brekkes Blick, der eine",
            "Winzigkeit zu lange auf einem Absatz des Manuskripts ruht.",
            "Bei der internen Abnahme reagiert Brekke kühl, mehrdeutig",
            "— und verlangt „kleine Anpassungen\", die exakt jene",
            "Stellen betreffen, in die Konrad seine leisesten Zweifel",
            "eingeschrieben hatte.",
            "",
            "Es gibt kein sauberes Ende. Die Sendung geht wie geplant",
            "auf Sendung — das Publikum hört, was Konrad nur ahnt: Am",
            "Jubiläumstag ändert sich nichts, das Fest findet statt,",
            "wie es immer stattgefunden hätte. Konrad bleibt in der",
            "Redaktion, tiefer im Apparat als je zuvor, respektiert,",
            "unersetzlich — und unfähig zu sagen, ob der letzte Blick,",
            "den Brekke ihm beim Hinausgehen zuwirft, Vertrauen",
            "bedeutet oder eine Frist mit Aufschub. Die Maske ist jetzt",
            "sein Gesicht. Das Jubiläum hat gerade erst begonnen.",
            "",
            "── Ende ────────────────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "03_figuren.txt",
          kind: "text",
          size: 6100,
          date: "18.09.1997",
          content: [
            "── 2. FIGURENPROFILE ───────────────────────────────────────",
            "",
            "2. Detaillierte Figurenprofile",
            "",
            "Konrad Fenner",
            "",
            "Alter: 41 Jahre (Stand Herbst 1996).",
            "",
            "Funktion: Redakteur, Ressort Sektorbericht, ZDS — und, im",
            "Verborgenen, seit mehreren Jahren informeller Verwahrer",
            "ausgesonderter Aktenbestände.",
            "",
            "Herkunft",
            "",
            "1955 im Sektor 28 geboren, als Sohn eines der ersten",
            "Registraturbeamten der Mandatsverwaltung. Studium der",
            "Verwaltungswissenschaften an der Zentralausbildungsstätte,",
            "danach, fast zwangsläufig, der Eintritt in die ZDS-",
            "Redaktion. 1978 — das ist der Angelpunkt seiner gesamten",
            "psychologischen Statik — trat er nicht zynisch, sondern",
            "ergriffen in den Sektorbericht ein. Er glaubte, kurz und",
            "aufrichtig, an die beruhigende Kraft der guten, sauberen",
            "Meldung. Die Ernüchterung kam nicht als einzelner Schock,",
            "sondern als langsame Erosion, bis sich die Beruhigung als",
            "Lack über etwas Unausgesprochenem entpuppte.",
            "",
            "Zentraler innerer Konflikt",
            "",
            "Genau diese Vorgeschichte macht ihn zum idealen, stillen",
            "Verwahrer — und zum gefährdetsten zugleich. Andere in",
            "seiner Lage würden eine Rolle spielen, die ihnen fremd",
            "ist; Konrad spielt eine Rolle, die er einmal tatsächlich",
            "war. Wenn er vor Brekke von Zuversicht spricht, greift er",
            "auf echte, einmal empfundene Überzeugung zurück und",
            "verschiebt nur das Ziel. Die eigentliche dramaturgische",
            "Gefahr ist deshalb nicht Entdeckung durch andere, sondern",
            "Entdeckung durch sich selbst: die Angst, dass die",
            "Wiederholung der Maske sie irgendwann zum Gesicht macht.",
            "",
            "Wunder Punkt",
            "",
            "Sein Vater, mittlerweile im Ruhestand, glaubt bis heute",
            "uneingeschränkt an die Erzählung, die Konrad zunehmend",
            "infrage stellt — ein Mann, der die Gründung selbst",
            "mitverwaltet hat und darin, im Gegensatz zu seinem Sohn,",
            "nie etwas anderes sah als ein gutes, ordentliches Werk.",
            "Diese Kluft wird im Stück bewusst nicht geschlossen; sie",
            "ist bereits bezahlter Preis, lange bevor die eigentliche",
            "Handlung beginnt, und wird im dritten Akt durch eine",
            "beiläufige, nie verifizierte Bemerkung Brekkes schlagartig",
            "reaktiviert.",
            "",
            "Fähigkeiten",
            "",
            "Präzises Aktenlesen, geschult durch Jahre der",
            "Redaktionsarbeit — er versteht, wie eine Erzählung gebaut",
            "wird, weil er ihr Handwerkszeug täglich selbst benutzt.",
            "Das macht ihn zum ebenbürtigen Gegenüber Brekkes — und",
            "zugleich zur Zielscheibe von dessen Misstrauen: Ein Mann,",
            "der eine Erzählung so überzeugend zusammensetzt wie er",
            "selbst, ist für Brekke nie ganz ohne Vorbehalt zu",
            "vertrauen, so sehr er ihn auch schätzt.",
            "",
            "Oberrat Brekke",
            "",
            "Funktion: Chefredaktion, ZDS-Sektorbericht, mit Zugriff",
            "auf gesperrte Zentralarchivbestände.",
            "",
            "Dramaturgische Grundhaltung",
            "",
            "Diese Figur wird bewusst nicht als kalter Bürokraten-",
            "Schrecken oder Karikatur angelegt. Brekke versteht sich",
            "selbst als Kurator, nicht als Zensor — jemand, der glaubt,",
            "dass eine funktionierende Erzählung mehr Menschen schützt",
            "als eine vollständige. Genau dieser Zug macht ihn zum",
            "gefährlichsten Gegenüber, das man Konrad gegenüberstellen",
            "kann: Ein Mann, der Nuancen goutieren kann, ist ein Mann,",
            "der Konrads Konzept goutiert, ohne dessen zweiten Boden",
            "zwangsläufig zu durchschauen — was die Bedrohung nicht",
            "mindert, sondern erhöht.",
            "",
            "Psychologisches Instrumentarium",
            "",
            "Brekke führt Gespräche wie Aktenprüfungen, die sich als",
            "Plaudereien tarnen. Er platziert beiläufig Detailwissen —",
            "ein Datum, ein Aktenzeichen, einen Namen —, um Reaktionen",
            "zu testen, nicht um Informationen zu gewinnen, die er",
            "längst besitzt. Er belohnt Nähe mit noch gefährlicherer",
            "Nähe: einer Andeutung, einem Aktenfragment, einem",
            "Geheimnis — denn geteiltes Wissen bindet stärker als jede",
            "Unterschrift. Wer mitweiß, ist Mitwisser, und",
            "Mitwisserschaft ist die einzige Loyalität, der er wirklich",
            "traut.",
            "",
            "Wiederkehrendes Motiv",
            "",
            "Brekke denkt in Sendeformaten, auch wenn er über",
            "Verwaltungsgeschichte spricht: fünfzig Jahre als",
            "Erzählbogen, das Jubiläum als dramaturgischer Höhepunkt,",
            "der noch die richtige Auflösung braucht. Diese Denkfigur",
            "nimmt in der ausgearbeiteten Szene (Abschnitt 5) wörtlich",
            "Gestalt an und ist der eigentliche Schlüssel zu seiner",
            "Darstellung: Das Beunruhigende liegt nicht im Befehlston,",
            "sondern in der ruhigen, redaktionell geschulten Präzision,",
            "mit der er über fünfzig Jahre verwalteten Lebens spricht",
            "wie über eine Schnittfassung.",
            "",
            "Torben & Nele Pahl",
            "",
            "Funktion: Hausmeister-Ehepaar im Wohnblock des",
            "Zentralarchivs, Konrads erste zivile Verbündete.",
            "",
            "Ausgangssituation",
            "",
            "Torben, Hausmeister mit Schlüsselgewalt über die",
            "Kellerräume, gerät durch eine unbedachte Bemerkung über",
            "die „ewige Vorläufigkeit\" bei einer Hausversammlung in",
            "eine unangenehme Lage — und in Konrads nächtliche",
            "Recherche hinein, der ihn zunächst für einen Kontrolleur",
            "hält und entsprechend behandelt, um ihn dann, unter vier",
            "Augen, mit einem einzigen Satz zu beruhigen. Beklemmung,",
            "gefolgt von unverhoffter Offenheit: Dieser Moment ist der",
            "emotionale Gründungsvertrag der Beziehung.",
            "",
            "Nele — die aktivere, klügere Kraft des Paares",
            "",
            "Die Dramaturgie vermeidet bewusst das Klischee der bangen,",
            "passiven Ehefrau. Nele liefert die konkreten, klugen",
            "Vorschläge — den unauffälligen Ablageort in der",
            "stillgelegten Rohrpost-Station, die Idee, die",
            "Kellerbelegungspläne so zu führen, dass Konrads nächtliche",
            "Besuche darin verschwinden. Sie wird durchgehend als",
            "ebenbürtige, moralisch treibende Kraft geführt, nicht als",
            "Anhängsel Torbens.",
            "",
            "Vorsicht als Motor, nicht als Bremse",
            "",
            "Beide handeln nicht, weil die Vorsicht verschwindet,",
            "sondern obwohl sie bleibt. Jede Zusage ist ein kleiner",
            "Sieg über das eigene Zögern, nie ein Zeichen von",
            "Unbekümmertheit.",
            "",
            "── Ende ────────────────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "04_struktur_drei_akte.txt",
          kind: "text",
          size: 7400,
          date: "05.10.1997",
          content: [
            "── 3. TREATMENT-STRUKTUR ───────────────────────────────────",
            "",
            "3. Treatment-Struktur (Drei-Akt-Modell)",
            "",
            "Akt I — Ausgangslage (ca. Minute 1–16)",
            "",
            "Sektor 28, Herbst 1996. Der Bürgerfunk kündigt die",
            "kommende Jubiläumssendung an; im Treppenhaus mischt sich",
            "Vorfreude mit einem Unterton, den niemand laut ausspricht.",
            "Wir lernen Konrad Fenner in seinem Element kennen: in der",
            "Redaktion, kompetent, unauffällig, ein Mann, der genau die",
            "Sätze liefert, die man von ihm erwartet. Eine erste,",
            "knappe Begegnung mit Brekke bei einer Redaktionssitzung",
            "etabliert die Statik der gesamten Geschichte: den",
            "prüfenden Blick des Oberrats, sein Bedürfnis,",
            "Zuverlässigkeit nicht zu glauben, sondern zu testen. Eine",
            "beiläufig fallende Bemerkung über „unbedachte",
            "Wortmeldungen\" im Sektor pflanzt den ersten Samen.",
            "",
            "In einer privaten Szene sehen wir die andere Hälfte von",
            "Konrads Leben: die stille Routine seiner Ablage — ein auf",
            "Unauffälligkeit trainierter Aktenordner, ein System, das",
            "ihm selbst nicht mehr ganz erlaubt zu sagen, wonach er",
            "eigentlich sucht. Wir verstehen: Konrads größter Schutz",
            "ist, dass er selbst nicht genau weiß, wofür er das alles",
            "aufbewahrt.",
            "",
            "Erster Wendepunkt: Konrad schlägt Brekke ein Sendekonzept",
            "vor, das nicht die Feiernden, sondern die zunehmend",
            "Erschöpften erreichen soll. Brekke, selbst ein Verfechter",
            "subtilerer Formate, ist sofort angetan — und betraut",
            "Konrad mit der Leitung. Ein Danaergeschenk: Nie war Konrad",
            "näher am Zentralarchiv, nie war er verwundbarer.",
            "",
            "Bei der anschließenden Kellerrecherche eskaliert eine",
            "harmlose Verwechslung gefährlich: Konrad, gezwungen zu",
            "improvisieren, gibt sich für einen Moment als Kontrolleur",
            "aus, um den verängstigten Hausmeister Torben Pahl zu",
            "„befragen\". Erst unter vier Augen löst er die Verwechslung",
            "auf. Aus Beklemmung wird, behutsam und über mehrere Szenen",
            "aufgebaut, ein erstes ziviles Bündnis: Torben und seine",
            "Frau Nele werden zu Konrads ersten Verbündeten außerhalb",
            "der Redaktion.",
            "",
            "Akt-Ende: Konrad hat Zugang, Auftrag und erste Verbündete",
            "gewonnen — aber eine Kollegin aus der Kellerszene, die",
            "fluchtartig den Gang verließ, bleibt als offene, nie ganz",
            "aufgelöste Unsicherheit im Raum stehen. Eine doppelte Uhr",
            "beginnt zu ticken.",
            "",
            "Akt II — Verdichtung (ca. Minute 16–52)",
            "",
            "Der zweite Akt verschränkt zwei Handlungsstränge.",
            "",
            "Strang A — Die Sendung als Werkzeug",
            "",
            "Konrads Konzept nimmt Gestalt an: kein Triumphbogen,",
            "sondern ein Jubiläum, das die eigene Vorläufigkeit offen",
            "benennt — nicht als Anklage, sondern (so das offizielle",
            "Argument) als ehrlichere, deshalb wirksamere Form der",
            "Feier. Die Chefredaktion, die das Sendemanuskript",
            "begleitet, ist nicht die naheliegende Wahl, sondern die",
            "besonders wachsame Redakteurin Ines Corvath — eine",
            "bewusste Erschwernis: Jede leise Abweichung muss an einer",
            "Frau vorbei, deren Beruf es ist, genau solche Abweichungen",
            "zu erkennen. Konrad entwickelt eine Strategie der",
            "Gradualität: so klein beginnen, dass Corvath sich an den",
            "Ton gewöhnt, bevor sie ihn bemerkt.",
            "",
            "Mittelpunkt-Wendepunkt (ca. Minute 32): In einem kühlen",
            "Vier-Augen-Gespräch — der in Abschnitt 5 vollständig",
            "ausgearbeiteten Schlüsselszene — zieht Brekke Konrad enger",
            "in sein Vertrauen, als dieser sich je erhofft oder",
            "gefürchtet hat. Er zeigt ihm ein Aktenfragment aus dem",
            "Jahr der Quadranten-Konvention: Belege, dass eine echte",
            "Souveränität 1971 verhandelbar gewesen wäre — und dass",
            "sich die Verwaltung aktiv dagegen entschied. Das geteilte",
            "Wissen ist keine Belohnung, sondern eine Fessel — und im",
            "gleichen Atemzug fordert Brekke das fertige",
            "Sendemanuskript als Pfand.",
            "",
            "Strang B — Der Preis des Wissens",
            "",
            "Was folgt, ist eine der spannungsreichsten Passagen des",
            "Hörspiels: die Übermittlung einer Abschrift über die",
            "stillgelegte Rohrpost-Station, unter der ausdrücklichen",
            "Selbstauflage, sie nicht leichtfertig weiterzugeben — eine",
            "Szene, die Konrads eigenständiges Urteil zeigt, nicht nur",
            "seine Funktion als Verwahrer. Eine Antwort kommt nie. Die",
            "Stille, die folgt, wird zur eigentlichen Antagonistin der",
            "zweiten Akthälfte — lauter als jede Verfolgung, weil sie",
            "Konrad zwingt, mit einer Ungewissheit zu leben, die er",
            "nicht auflösen kann.",
            "",
            "Während die Sendung voranschreitet, verdichten sich",
            "kleine, nie eindeutige Zeichen der Beobachtung: eine",
            "Frage, die eine Kollegin zu genau stellt; die Rohrpost-",
            "Station, die einmal anders aussieht, als Konrad sie",
            "verlassen hat; Corvaths Blick, der eine Winzigkeit zu",
            "lange auf einem Absatz ruht. Nichts davon wird aufgelöst —",
            "das Treatment nutzt diese Häufung bewusst zur Erzeugung",
            "von Ungewissheit, nicht zur Konstruktion eines eindeutigen",
            "Verräters.",
            "",
            "Akt-Ende (Tiefpunkt): Die interne Abnahme des fertigen",
            "Manuskripts vor Brekke. Seine Reaktion ist unlesbar. Er",
            "verlangt „kleine Anpassungen\" — und diese betreffen exakt",
            "jene Passagen, in die Konrad seine leisesten Zweifel",
            "eingeschrieben hatte. Zeitgleich erreicht Konrad eine",
            "unbestätigte Andeutung, dass sein Vater bei einer",
            "Routineprüfung „aufgefallen\" sei. Beide Fäden —",
            "redaktionell und familiär — laufen im tiefsten Punkt der",
            "Geschichte zusammen.",
            "",
            "Akt III — Auflösung (ca. Minute 52–70)",
            "",
            "Der dritte Akt komprimiert zwei parallele Fristen auf",
            "ihren gemeinsamen Nullpunkt: die endgültige Freigabe der",
            "Sendung und den Jubiläumstermin selbst.",
            "",
            "Brekke erteilt die Freigabe — mit Auflagen, mit stiller,",
            "nie ausgesprochener Beobachtung. Konrad wird in der",
            "Redaktion als der Mann anerkannt, der dem Jubiläum einen",
            "menschlichen, glaubwürdigen Ton gegeben hat; im",
            "Verborgenen muss er in denselben Tagen die letzte",
            "Abschrift des Aktenfragments sichern und über die",
            "Rohrpost-Station weiterleiten — unter einer",
            "Beobachtungsdichte, die keine der etablierten Routinen",
            "mehr zulässt.",
            "",
            "Klimax: Die Sequenz montiert zwei Räume gegeneinander: den",
            "Redaktionsraum, in dem Konrad öffentliche Anerkennung",
            "entgegennimmt — und den Kellerabgang zur Rohrpost-Station",
            "in der Dämmerung, in dem eine letzte, unauffällige",
            "Übergabe stattfindet, während eine Gestalt, deren",
            "Zugehörigkeit nie ganz geklärt wird, im Treppenhaus",
            "verweilt. Die Auflösung verzichtet bewusst auf klassische",
            "Spannungsmittel zugunsten von Nervenspannung: Timing,",
            "Beherrschung der eigenen Stimme, ein Wortwechsel auf",
            "Messers Schneide.",
            "",
            "Auflösung: Die Abschrift geht hinaus, in die Rohrpost, ins",
            "Ungewisse. Eine Bestätigung, ob sie irgendetwas verändert",
            "hat, wird es nie geben. Die Jubiläumssendung läuft wie",
            "geplant, mit stehenden Ovationen im Bürgerfunk-Studio. In",
            "der letzten Sequenz sehen wir Konrad, äußerlich",
            "unversehrt, tiefer im Apparat als je zuvor, geschätzt und",
            "zugleich — das bleibt in der Schwebe — vielleicht",
            "durchschaut. Ein letzter, undeutbarer Blick Brekkes beim",
            "Hinausgehen lässt offen, ob es Vertrauen ist oder eine",
            "Frist mit Aufschub. Das Hörspiel endet nicht mit",
            "Befreiung, sondern mit einem Mann, der seine eigene Stimme",
            "im Kopfhörer-Rückkanal nicht mehr von seiner tatsächlichen",
            "unterscheiden kann — während im Hintergrund die",
            "Bürgerfunk-Anmoderation des Jubiläumsjahres läuft,",
            "unverändert, wie geplant.",
            "",
            "── Ende ────────────────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "05_anmerkung_des_autors.txt",
          kind: "text",
          size: 2600,
          date: "21.10.1997",
          content: [
            "── 4. ANMERKUNG DES AUTORS ─────────────────────────────────",
            "",
            "4. Anmerkung des Autors",
            "",
            "Warum diese Geschichte",
            "",
            "Ich arbeite seit elf Jahren in der",
            "Informationsbeschaffung, Sektor 28. Ich lese Akten, damit",
            "andere entscheiden können, was mit ihnen geschieht. Das",
            "ist keine Klage — ich habe diese Arbeit nie als Zumutung",
            "empfunden, eher als eine Art Beruhigung, von der ich",
            "lieber nicht zu genau wissen möchte, wie sie funktioniert.",
            "",
            "Was mich an dieser Geschichte interessiert hat, war nicht",
            "die Frage, ob Konrad recht hat. Es ist die Frage, die mich",
            "in meiner eigenen Arbeit gelegentlich streift, wenn ich",
            "einen alten Vorgang länger ansehe, als das Formular es",
            "verlangt: ob man einem Vorgang dient oder ihm",
            "widerspricht, wenn man ihn nur besonders sorgfältig",
            "bearbeitet. Dieses Stück behauptet keine Antwort. Es",
            "behauptet nur, dass die Frage gestellt werden darf, auch",
            "wenn — gerade weil — sie im Feld für Bemerkungen keinen",
            "Platz hat.",
            "",
            "Zum Ton",
            "",
            "TOTER BRIEFKASTEN soll nicht laut sein. Kein Verhör, kein",
            "Fluchtweg, keine Verfolgung — die Bedrohung dieser",
            "Geschichte trägt keine Uniform und erhebt nie die Stimme.",
            "Sie sitzt am Schreibtisch gegenüber und meint es, soweit",
            "erkennbar, gut.",
            "",
            "Zur Form",
            "",
            "Ich habe mich für ein Hörspiel entschieden, nicht für",
            "Prosa, weil das, worum es geht — eine Stimme, die zu gut",
            "wird in dem, was sie vorgibt zu fühlen —, sich im reinen",
            "Ton entscheidet, nicht im Bild. Man soll Konrad nicht",
            "ansehen können, ob er lügt. Man soll es nur hören, und",
            "selbst dann nicht sicher sein.",
            "",
            "Der dramaturgische Kniff",
            "",
            "Das moralische Zentrum liegt nicht in Konrads Mut, sondern",
            "in seinem Zweifel: eine Sendung, die gut genug ist, um die",
            "Erzählung zu unterwandern, ist unweigerlich auch gut",
            "genug, um ihr zu dienen. Ich weiß nicht, ob das für mich",
            "selbst auch gilt. Ich habe aufgehört, mir sicher zu sein,",
            "dass es einen Unterschied macht.",
            "",
            "── Ende ────────────────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "06_szene_aktenfragment.txt",
          kind: "text",
          size: 9200,
          date: "09.11.1997",
          content: [
            "── 5. AUSGEARBEITETE SZENE ─────────────────────────────────",
            "",
            "Schlüsselszene aus Akt II — Mittelpunkt-Wendepunkt („Das",
            "Aktenfragment\"). Hörspielformat.",
            "",
            "ATMO: Vorzimmer. Ein Terminal im Ruhemodus surrt leise.",
            "Eine Uhr tickt.",
            "",
            "INSA (Brekkes Sekretärin, ohne von der Schreibmaschine",
            "aufzusehen)",
            "Er weiß, dass Sie da sind.",
            "",
            "(Konrad setzt sich nicht. Man hört ihn stehen bleiben —",
            "ein leises Verlagern von Gewicht, ein Räuspern, das er",
            "sofort unterdrückt.)",
            "",
            "GERÄUSCH: Eine Tür öffnet sich, ferngesteuert, mit leisem",
            "Summen.",
            "",
            "ATMO-WECHSEL: Brekkes Büro. Größerer Raum, mehr Hall.",
            "Papier raschelt.",
            "",
            "BREKKE (ohne aufzusehen, das Rascheln geht weiter)",
            "Setzen Sie sich, Fenner.",
            "",
            "(Ein Stuhl wird gerückt. Das Rascheln endet — ein Stift",
            "wird exakt neben ein Blatt gelegt.)",
            "",
            "BREKKE (fortfahrend)",
            "Schreibt Ihnen Ihr Vater noch? Aus dem Sektor sechzehn?",
            "",
            "(Pause. Kaum eine Sekunde. Aber jede zählt jetzt.)",
            "",
            "KONRAD",
            "Wir telefonieren, Oberrat. Selten.",
            "",
            "BREKKE",
            "Schade. Er war einer der Ersten, wissen Sie. 1946. Er hat",
            "mit aufgebaut, was Sie heute verwalten.",
            "",
            "(Beat)",
            "",
            "Aber Sie haben hier offenbar Ihre eigene Aufgabe gefunden.",
            "",
            "KONRAD",
            "Das würde ich mir nicht anmaßen zu behaupten. Ich bin",
            "dankbar für das Vertrauen, das man mir entgegenbringt.",
            "",
            "(Brekke lehnt sich zurück — man hört das Leder des",
            "Stuhls.)",
            "",
            "BREKKE",
            "Ich habe die letzten Seiten gelesen.",
            "",
            "(tippt auf Papier)",
            "",
            "Die Passage, in der die alte Frau aus E-Trakt sagt, sie",
            "erinnere sich nicht mehr, ob es vor oder nach der Gründung",
            "war, dass sie zum letzten Mal wählen durfte. Das ist",
            "gewagt, Fenner.",
            "",
            "KONRAD",
            "Ein Zweifel, den die Sendung auflöst, Oberrat. Am Ende der",
            "Passage steht die Feier stärker da als zuvor.",
            "",
            "BREKKE",
            "Das weiß ich. Ich habe es gelesen.",
            "",
            "(Beat, dann leiser)",
            "",
            "Ich frage mich nur, woher Sie so genau wissen, wie sich",
            "eine Erinnerung anfühlt, die man nicht mehr ganz zu fassen",
            "bekommt.",
            "",
            "(Stille. Durch die Wand: die Standuhr im Vorzimmer.)",
            "",
            "KONRAD",
            "Ich schreibe seit achtzehn Jahren für dieses Ressort,",
            "Oberrat. Ich kenne den Ton von innen.",
            "",
            "(Brekke lacht kurz, trocken.)",
            "",
            "BREKKE",
            "Gut gesagt.",
            "",
            "(Schritte — er steht auf, geht zum Fenster.)",
            "",
            "Wissen Sie, was mich an diesem Handwerk am meisten gereizt",
            "hat, damals, als ich selbst noch Sendungen schrieb? Nicht",
            "die große Ansage. Die kleine Regieanweisung im Manuskript.",
            "„Pause.\" „Stimme wird wärmer, ohne dass sie es merkt.\"",
            "",
            "(dreht sich um)",
            "",
            "Mit sieben Worten kann man eine ganze Sektorstimmung",
            "erschaffen. Oder auflösen.",
            "",
            "KONRAD (vorsichtig)",
            "Ein mächtiges Handwerk.",
            "",
            "BREKKE",
            "Das mächtigste, das wir besitzen. Mächtiger als jede",
            "Verordnung.",
            "",
            "(Er kommt zurück, bleibt stehen, über Konrad aufragend.)",
            "",
            "BREKKE (fortfahrend)",
            "Zeigen Sie mir etwas, Fenner. Die Zeile auf Seite zwölf.",
            "Sprechen Sie sie, wie die Sprecherin sie sprechen soll.",
            "",
            "KONRAD",
            "Hier? Ich bin kein Sprecher, Oberrat.",
            "",
            "BREKKE",
            "Jeder in diesem Haus ist Sprecher. Ich möchte nur wissen,",
            "für welchen Ton Sie besetzt sind.",
            "",
            "(Ein Moment. Papier wird umgeblättert.)",
            "",
            "KONRAD (mit ruhiger, tragender Wärme)",
            "„Fünfzig Jahre vorläufig zu sein, heißt nicht, dass man",
            "auf etwas wartet. Es heißt, dass man gelernt hat, im",
            "Warten zu wohnen.\"",
            "",
            "(Stille. Man hört Brekke nicht — nur das Fehlen jedes",
            "Geräuschs, eine Spur zu lange.)",
            "",
            "BREKKE (leise)",
            "Noch einmal. Langsamer.",
            "",
            "KONRAD (wiederholt, eine Nuance wärmer)",
            "„Fünfzig Jahre vorläufig zu sein... heißt nicht, dass man",
            "auf etwas wartet. Es heißt, dass man gelernt hat, im",
            "Warten zu wohnen.\"",
            "",
            "(Ein langes Schweigen. Der Stuhl knarrt — Brekke setzt",
            "sich wieder.)",
            "",
            "BREKKE",
            "Der Mandatsrat sagt es selbst: Das Gebiet braucht",
            "Kontinuität. Nicht Metaphern — Kontinuität. Stabile",
            "Sektoren, verlässliche Kontingente, eine Verwaltung, die",
            "sich fünfzig Jahre lang nicht geirrt haben darf.",
            "",
            "(Beat)",
            "",
            "Ein unbeschriebenes Kapitel, könnte man sagen. Das darauf",
            "wartet, dass endlich jemand die richtige Fortsetzung",
            "hineinschreibt.",
            "",
            "KONRAD (sehr ruhig, sehr vorsichtig)",
            "Und die Konvention von einundsiebzig, Oberrat?",
            "",
            "(Ein Blick von Brekke, scharf, prüfend — man hört es fast",
            "im veränderten Atem.)",
            "",
            "BREKKE",
            "Einundsiebzig war... ein Kapitel, das man anders hätte",
            "schreiben können.",
            "",
            "(Beat)",
            "",
            "Man hat sich dagegen entschieden. Aus guten Gründen. Aus",
            "verwaltbaren Gründen.",
            "",
            "(Er setzt sich, langsam, kontrolliert.)",
            "",
            "BREKKE (fortfahrend)",
            "Was ich Ihnen jetzt sage, verlässt diesen Raum nicht. Und",
            "verstehen Sie mich richtig: Ich sage es Ihnen nicht, weil",
            "Sie es wissen müssen. Ich sage es Ihnen, damit Sie wissen,",
            "was Sie ab sofort sind.",
            "",
            "KONRAD",
            "Was bin ich, Oberrat?",
            "",
            "BREKKE",
            "Mitwisser.",
            "",
            "(Er lässt das Wort im Raum stehen.)",
            "",
            "BREKKE (fortfahrend)",
            "Und Mitwisser tragen die Sache mit sich, ob sie wollen",
            "oder nicht. Das ist keine Drohung, Fenner. Das ist",
            "Aktenlage.",
            "",
            "KONRAD",
            "Ich verstehe.",
            "",
            "BREKKE",
            "Ihre Sendung läuft am Jubiläumstag. Die Leute werden müde",
            "sein von fünfzig Jahren desselben Tons. Sie werden eine",
            "Stimme hören wollen, die auch einmal zweifelt — gerade",
            "dann.",
            "",
            "(tippt auf Papier)",
            "",
            "Ihre Zweifelspassage könnte genau das sein, was der Sektor",
            "in diesem Moment braucht. Oder ein Fehler, den ich niemals",
            "hätte zulassen dürfen.",
            "",
            "KONRAD",
            "Ich bin bereit, dieses Risiko mit Ihnen zu tragen,",
            "Oberrat.",
            "",
            "BREKKE",
            "Mit mir?",
            "",
            "(Ein dünnes Lächeln, hörbar in der Stimme.)",
            "",
            "BREKKE (fortfahrend)",
            "Nein, Fenner. Für mich. Das Risiko trage weiterhin ich.",
            "Sie tragen die Folgen.",
            "",
            "(Beat.)",
            "",
            "Ich will das vollständige Manuskript. In sieben Tagen.",
            "",
            "KONRAD",
            "Sieben Tage sind —",
            "",
            "BREKKE",
            "Sieben Tage sind, was die Lage erlaubt.",
            "",
            "(Schritte — er steht auf, umrundet den Schreibtisch,",
            "öffnet Konrad selbst die Tür.)",
            "",
            "BREKKE (fortfahrend)",
            "Sie besitzen ein seltenes Talent, Fenner. Sie schreiben",
            "Zuversicht, als hätten Sie sie nie verloren.",
            "",
            "(An der Tür, näher, leiser.)",
            "",
            "BREKKE (fortfahrend)",
            "Ich hoffe für Sie, dass das auch stimmt.",
            "",
            "(Tür bleibt offen. Wartet.)",
            "",
            "KONRAD",
            "Einen guten Abend, Oberrat.",
            "",
            "BREKKE",
            "Einen guten Abend.",
            "",
            "GERÄUSCH: Die Tür schließt sich — leise, aber endgültig.",
            "",
            "ATMO: Korridor. Schritte, die verklingen, dann anhalten.",
            "",
            "(Konrad steht allein. Erst jetzt, außerhalb jeder",
            "Sichtlinie — und, das darf man in einem Hörspiel ruhig",
            "offenlassen, vielleicht auch außerhalb jeder Hörweite —",
            "erlaubt sich seine Stimme, wenn er leise für sich spricht,",
            "ein kaum hörbares Zittern.)",
            "",
            "KONRAD (sehr leise, zu sich selbst)",
            "Aktenlage.",
            "",
            "(Schritte setzen sich fort — im exakt selben, gemessenen",
            "Takt, mit dem er gekommen ist.)",
            "",
            "ENDE DER SZENE",
            "",
            "── Ende ────────────────────────────────────────────────────",
          ],
        },
      ],
    },
  ],
};
